collections:
  dungeons-and-dragons:
    output: true
  posts:
    output: true
  recipes:
    output: true
collections_dir: "collections"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
